const MODEL_URL="https://justadudewhohacks.github.io/face-api.js/models";
const imageInput=document.getElementById("imageInput"),dropZone=document.getElementById("dropZone"),imageWrapper=document.getElementById("imageWrapper"),imageStatus=document.getElementById("imageStatus"),personName=document.getElementById("personName"),resultsContainer=document.getElementById("resultsContainer"),totalFaces=document.getElementById("totalFaces"),analysisStatus=document.getElementById("analysisStatus"),loadingOverlay=document.getElementById("loadingOverlay"),loadingText=document.getElementById("loadingText"),video=document.getElementById("video"),videoCanvas=document.getElementById("videoCanvas"),cameraPlaceholder=document.getElementById("cameraPlaceholder"),cameraButton=document.getElementById("cameraButton");
let modelsLoaded=false,stream=null,cameraRunning=false,detectionLoop=null,processingCamera=false;
const reactionData={happy:{label:"Happy",icon:"😊"},sad:{label:"Sad",icon:"😢"},angry:{label:"Angry",icon:"😠"},surprised:{label:"Surprised",icon:"😮"},fearful:{label:"Fearful",icon:"😨"},disgusted:{label:"Disgusted",icon:"🤢"},neutral:{label:"Neutral",icon:"😐"}};

async function loadModels(){if(modelsLoaded)return;showLoading("Loading AI models...");try{await faceapi.nets.tinyFaceDetector.loadFromUri(MODEL_URL);await faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL);await faceapi.nets.ageGenderNet.loadFromUri(MODEL_URL);await faceapi.nets.faceExpressionNet.loadFromUri(MODEL_URL);modelsLoaded=true}catch(error){console.error(error);alert("AI models could not be loaded. Check your internet connection and try again.");throw error}finally{hideLoading()}}
window.addEventListener("load",async()=>{try{await loadModels()}catch(e){console.error(e)}});

imageInput.addEventListener("change",async function(){if(this.files[0])await processImageFile(this.files[0])});
dropZone.addEventListener("dragover",e=>{e.preventDefault();dropZone.style.borderColor="#6366f1"});
dropZone.addEventListener("dragleave",()=>dropZone.style.borderColor="");
dropZone.addEventListener("drop",async e=>{e.preventDefault();dropZone.style.borderColor="";const file=e.dataTransfer.files[0];if(!file)return;if(!file.type.startsWith("image/"))return showError("Please select a valid image file.");await processImageFile(file)});

async function processImageFile(file){try{if(!modelsLoaded)await loadModels();showLoading("Analyzing faces...");const url=URL.createObjectURL(file),img=await faceapi.fetchImage(url);displayImage(img);await analyzeImage(img);URL.revokeObjectURL(url)}catch(error){console.error(error);showError("Unable to analyze this image.")}finally{hideLoading()}}
function displayImage(img){imageWrapper.innerHTML="";const el=document.createElement("img");el.src=img.src;el.id="uploadedImage";imageWrapper.appendChild(el);imageStatus.textContent="Analyzing";imageStatus.className="status waiting"}
async function analyzeImage(img){const options=new faceapi.TinyFaceDetectorOptions({inputSize:416,scoreThreshold:.45});const detections=await faceapi.detectAllFaces(img,options).withFaceLandmarks().withAgeAndGender().withFaceExpressions();drawImageResults(detections);updateResultsDashboard(detections)}
function drawImageResults(detections){const imageElement=document.getElementById("uploadedImage");if(!imageElement)return;const old=imageWrapper.querySelector(".result-canvas");if(old)old.remove();const canvas=faceapi.createCanvasFromMedia(imageElement);canvas.className="result-canvas";imageWrapper.appendChild(canvas);faceapi.matchDimensions(canvas,imageElement);const resized=faceapi.resizeResults(detections,imageElement);resized.forEach((r,i)=>{const box=r.detection.box;new faceapi.draw.DrawBox(box,{label:`Person ${i+1}`}).draw(canvas);const age=convertAgeToRange(Math.round(r.age)),gender=capitalize(r.gender),reaction=getDominantExpression(r.expressions);new faceapi.draw.DrawTextField([`Age: ${age}`,`Gender: ${gender}`,`Reaction: ${reaction.icon} ${reaction.label}`],{x:box.x,y:Math.max(box.y-75,0)}).draw(canvas)})}

async function startCamera(){try{if(!modelsLoaded)await loadModels();if(cameraRunning)return;showLoading("Starting camera...");stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:"user"},audio:false});video.srcObject=stream;video.style.display="block";cameraPlaceholder.style.display="none";cameraRunning=true;cameraButton.innerHTML="◉ Stop Camera";await video.play();await waitForVideo();videoCanvas.width=video.videoWidth;videoCanvas.height=video.videoHeight;startDetectionLoop();document.getElementById("camera").scrollIntoView({behavior:"smooth"})}catch(error){console.error(error);showError("Camera permission was denied or the camera is unavailable.")}finally{hideLoading()}}
function waitForVideo(){return new Promise(resolve=>{if(video.readyState>=2&&video.videoWidth>0)return resolve();video.addEventListener("loadedmetadata",()=>resolve(),{once:true})})}
function toggleCamera(){cameraRunning?stopCamera():startCamera()}
function stopCamera(){cameraRunning=false;processingCamera=false;if(detectionLoop)clearTimeout(detectionLoop);detectionLoop=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;video.style.display="none";cameraPlaceholder.style.display="grid";cameraButton.innerHTML="◉ Start Camera";const ctx=videoCanvas.getContext("2d");ctx.clearRect(0,0,videoCanvas.width,videoCanvas.height);totalFaces.textContent="0";analysisStatus.textContent="Camera stopped"}
function startDetectionLoop(){async function detect(){if(!cameraRunning)return;if(!processingCamera){processingCamera=true;try{await detectCameraFaces()}catch(e){console.error("Camera detection error:",e)}processingCamera=false}detectionLoop=setTimeout(detect,250)}detect()}
async function detectCameraFaces(){const options=new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.45});const detections=await faceapi.detectAllFaces(video,options).withFaceLandmarks().withAgeAndGender().withFaceExpressions();const ctx=videoCanvas.getContext("2d");ctx.clearRect(0,0,videoCanvas.width,videoCanvas.height);const resized=faceapi.resizeResults(detections,{width:video.videoWidth,height:video.videoHeight});resized.forEach((r,i)=>{const box=r.detection.box,age=convertAgeToRange(Math.round(r.age)),gender=capitalize(r.gender),reaction=getDominantExpression(r.expressions);new faceapi.draw.DrawBox(box,{label:`Person ${i+1} • ${age} • ${gender} • ${reaction.icon}`}).draw(videoCanvas)});updateCameraDashboard(detections);totalFaces.textContent=detections.length;analysisStatus.textContent=detections.length?"Faces detected":"Scanning"}
function updateResultsDashboard(detections){totalFaces.textContent=detections.length;if(!detections.length){analysisStatus.textContent="No faces";imageStatus.textContent="No face";imageStatus.className="status error";resultsContainer.innerHTML=`<div class="no-results"><h3>No face detected</h3><p>Try another image with a clearly visible face.</p></div>`;return}analysisStatus.textContent="Analysis complete";imageStatus.textContent=`${detections.length} face(s) detected`;imageStatus.className="status success";resultsContainer.innerHTML="";detections.forEach((r,i)=>resultsContainer.appendChild(createResultCard(r,i)))}
function updateCameraDashboard(detections){if(!detections.length){resultsContainer.innerHTML=`<div class="no-results"><h3>No face detected</h3><p>Move closer to the camera or improve lighting.</p></div>`;return}resultsContainer.innerHTML="";detections.forEach((r,i)=>resultsContainer.appendChild(createResultCard(r,i)))}
function createResultCard(result,index){const card=document.createElement("div");card.className="result-card";const name=personName.value.trim()||`Person ${index+1}`,age=convertAgeToRange(Math.round(result.age)),gender=capitalize(result.gender),reaction=getDominantExpression(result.expressions),faceConfidence=result.detection.score,genderConfidence=result.genderProbability;card.innerHTML=`<div class="result-top"><div class="face-avatar">●</div><div><h3>${escapeHTML(name)}</h3><span class="face-detected">● Face Detected</span></div></div><div class="result-row"><span>Name</span><strong class="result-value">${escapeHTML(name)}</strong></div><div class="result-row"><span>Face</span><strong class="result-value">Detected</strong></div><div class="result-row"><span>Estimated Age</span><strong class="result-value">${age}</strong></div><div class="result-row"><span>Estimated Gender</span><strong class="result-value">${gender}</strong></div><div class="result-row"><span>Reaction</span><strong class="result-value reaction">${reaction.icon} ${reaction.label}</strong></div><div class="result-row"><span>Detection Confidence</span><strong class="result-value">${Math.round(faceConfidence*100)}%</strong></div><div class="result-row"><span>Gender Model Confidence</span><strong class="result-value">${Math.round(genderConfidence*100)}%</strong></div>`;return card}
function getDominantExpression(expressions){if(!expressions)return reactionData.neutral;let highest="neutral",value=expressions.neutral||0;Object.keys(expressions).forEach(k=>{if(expressions[k]>value){highest=k;value=expressions[k]}});return reactionData[highest]||reactionData.neutral}
function convertAgeToRange(age){const lower=Math.max(0,Math.floor(age/5)*5);return `${lower}–${lower+5}`}
function capitalize(text){return text?text.charAt(0).toUpperCase()+text.slice(1):"Unknown"}
function escapeHTML(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function showLoading(message){loadingText.textContent=message;loadingOverlay.classList.add("show")}
function hideLoading(){loadingOverlay.classList.remove("show")}
function showError(message){imageStatus.textContent="Error";imageStatus.className="status error";alert(message)}
function scrollToUpload(){document.getElementById("upload").scrollIntoView({behavior:"smooth"})}
window.addEventListener("beforeunload",()=>{if(stream)stream.getTracks().forEach(t=>t.stop())});
